import type { DatabaseSync } from 'node:sqlite';
import type { ApiKeyRecord, AuditEntry, IprsBackup, SessionRecord, SystemUser, UsageRecord, Wallet, WalletTransaction } from '../src/types/index.ts';

export const DB_PATH: string;
export const db: DatabaseSync;
export const CURRENT_SCHEMA_VERSION: number;
export const migrations: ReadonlyArray<{ version: number; up(database: DatabaseSync): void }>;

export function users(): SystemUser[];
export function findUser(id: string): SystemUser | null;
export function findUserByEmail(email: string): SystemUser | null;
export function putUser(user: SystemUser): SystemUser;
export function deleteUser(id: string): void;
export function wallets(): Wallet[];
export function walletFor(userId: string): Wallet | null;
export function walletById(id: string): Wallet | null;
export function putWallet(wallet: Wallet): Wallet;
export function transactions(userId?: string, limit?: number): WalletTransaction[];
export function putTransaction(transaction: Record<string, unknown>): Record<string, unknown>;
export function payments(filter?: Record<string, unknown>): Record<string, unknown>[];
export function paymentById(id: string): Record<string, unknown> | null;
export function putPayment(payment: Record<string, unknown>): Record<string, unknown>;
export function providers(): Record<string, unknown>[];
export function providerById(id: string): Record<string, unknown> | null;
export function putProvider(provider: Record<string, unknown>): Record<string, unknown>;
export function providerLogs(providerId?: string | null, limit?: number): Record<string, unknown>[];
export function putProviderLog(log: Record<string, unknown>): Record<string, unknown>;
export function apiKeys(): ApiKeyRecord[];
export function putApiKey(key: Record<string, unknown>): ApiKeyRecord;
export function auditLog(filter?: Record<string, unknown>): AuditEntry[];
export function appendAudit(entry: Record<string, unknown>): AuditEntry;
export function sessions(): SessionRecord[];
export function putSession(session: SessionRecord): SessionRecord;
export function deleteSession(id: string): void;
export function usageRecords(limit?: number): Array<UsageRecord & { apiKeyId?: string }>;
export function putUsage(record: UsageRecord): UsageRecord;
export function cases(): Record<string, unknown>[];
export function invoices(): Record<string, unknown>[];
export function notifications(): Record<string, unknown>[];
export function activities(): Record<string, unknown>[];
export function paymentMethods(): Record<string, unknown>[];
export function kvGet<T = unknown>(key: string, fallback?: T): T;
export function kvSet<T>(key: string, value: T): T;
export function settings<T = Record<string, unknown>>(): T;
export function saveSettings<T>(settings: T): T;
export function pricing<T = Record<string, unknown>>(): T;
export function savePricing<T>(pricing: T): T;
export function seedIfEmpty(): { seeded: boolean; counts?: Record<string, number> };
export function migrateDb(database?: DatabaseSync): { from: number; to: number; stamped: boolean };
export function createBackup(database?: DatabaseSync): IprsBackup;
export function restoreBackup(payload: unknown, database?: DatabaseSync): { format: 'iprs-backup'; version: 1; restored: true };
export function validateBackup(payload: unknown): IprsBackup['data'];
export function stats(): Record<string, number>;
