import React from 'react';
import {
  LogIn, LayoutDashboard, Search, UserCheck, FileBarChart2, Briefcase,
  BarChart3, CreditCard, Shield, Server, Layers, Code2, UserCog, Bell,
  Smartphone, LayoutGrid, ArrowRight, ChevronRight, ChevronDown, Home,
  Share2, ExternalLink, Check, X, Sparkles, MoreHorizontal, Settings,
  TrendingUp, TrendingDown, Users, FileCheck2, RotateCcw, User, Phone,
  Mail, ShieldAlert, Loader2, Calendar, MapPin, Download, Printer, Plus,
  Edit2, Trash2, Power, Activity, RefreshCw, KeyRound, Database, Lock,
  ShieldCheck, CheckCircle2, Info, AlertCircle, AlertTriangle,
} from 'lucide-react';

const ICON_SIZE = 16;

export const iconMap: Record<string, React.ReactNode> = {
  LogIn: <LogIn size={ICON_SIZE} />,
  LayoutDashboard: <LayoutDashboard size={ICON_SIZE} />,
  Search: <Search size={ICON_SIZE} />,
  UserCheck: <UserCheck size={ICON_SIZE} />,
  FileBarChart2: <FileBarChart2 size={ICON_SIZE} />,
  Briefcase: <Briefcase size={ICON_SIZE} />,
  BarChart3: <BarChart3 size={ICON_SIZE} />,
  CreditCard: <CreditCard size={ICON_SIZE} />,
  Shield: <Shield size={ICON_SIZE} />,
  Server: <Server size={ICON_SIZE} />,
  Layers: <Layers size={ICON_SIZE} />,
  Code2: <Code2 size={ICON_SIZE} />,
  UserCog: <UserCog size={ICON_SIZE} />,
  Bell: <Bell size={ICON_SIZE} />,
  Smartphone: <Smartphone size={ICON_SIZE} />,
  LayoutGrid: <LayoutGrid size={ICON_SIZE} />,
  ArrowRight: <ArrowRight size={ICON_SIZE} />,
  ChevronRight: <ChevronRight size={ICON_SIZE} />,
  ChevronDown: <ChevronDown size={ICON_SIZE} />,
  Home: <Home size={ICON_SIZE} />,
  Share2: <Share2 size={ICON_SIZE} />,
  ExternalLink: <ExternalLink size={ICON_SIZE} />,
  Check: <Check size={ICON_SIZE} />,
  X: <X size={ICON_SIZE} />,
  Sparkles: <Sparkles size={ICON_SIZE} />,
  MoreHorizontal: <MoreHorizontal size={ICON_SIZE} />,
  Settings: <Settings size={ICON_SIZE} />,
  TrendingUp: <TrendingUp size={ICON_SIZE} />,
  TrendingDown: <TrendingDown size={ICON_SIZE} />,
  Users: <Users size={ICON_SIZE} />,
  FileCheck2: <FileCheck2 size={ICON_SIZE} />,
  RotateCcw: <RotateCcw size={ICON_SIZE} />,
  User: <User size={ICON_SIZE} />,
  Phone: <Phone size={ICON_SIZE} />,
  Mail: <Mail size={ICON_SIZE} />,
  ShieldAlert: <ShieldAlert size={ICON_SIZE} />,
  Loader2: <Loader2 size={ICON_SIZE} />,
  Calendar: <Calendar size={ICON_SIZE} />,
  MapPin: <MapPin size={ICON_SIZE} />,
  Download: <Download size={ICON_SIZE} />,
  Printer: <Printer size={ICON_SIZE} />,
  Plus: <Plus size={ICON_SIZE} />,
  Edit2: <Edit2 size={ICON_SIZE} />,
  Trash2: <Trash2 size={ICON_SIZE} />,
  Power: <Power size={ICON_SIZE} />,
  Activity: <Activity size={ICON_SIZE} />,
  RefreshCw: <RefreshCw size={ICON_SIZE} />,
  KeyRound: <KeyRound size={ICON_SIZE} />,
  Database: <Database size={ICON_SIZE} />,
  Lock: <Lock size={ICON_SIZE} />,
  ShieldCheck: <ShieldCheck size={ICON_SIZE} />,
  CheckCircle2: <CheckCircle2 size={ICON_SIZE} />,
  Info: <Info size={ICON_SIZE} />,
  AlertCircle: <AlertCircle size={ICON_SIZE} />,
  AlertTriangle: <AlertTriangle size={ICON_SIZE} />,
};
